name: Publish package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish --access public   # remove --provenance for first publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
